### ISSUE TITLE
Add prefrence/settings activity to adjust hardcoded values

### ISSUE THREAD

**Issue by shantanu-vyas** [platypusllc/tablet#11]
Use androids preferences API to make a way to edit certain values such as MAX/MIN thrust, different speed PIDS etc.
This will be helpful for testing but should be disabled for users.

**Comment by psigen** [comment]
For reference, take a look at:

https://github.com/platypusllc/server/blob/feature/onetouch/app/src/main/java/com/platypus/android/server/SettingsFragment.java
https://github.com/platypusllc/server/blob/feature/onetouch/app/src/main/res/xml/preferences.xml

https://github.com/platypusllc/server/blob/feature/onetouch/app/src/main/java/com/platypus/android/server/LauncherFragment.java#L133

**Comment by shantanu-vyas** [comment]
The preference_api branch now has a settings activity where you can save and load all previously hard coded values. Debug was merged into this branch I'll do some testing and make sure everything is working before merging this back into debug.
