### ISSUE TITLE
PID displays as 0, 0, 0

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#22]
Can the tablet app display the default values when you navigate to the set PID option? Both the rudder and thrust PID values display as all zeroes.

**Comment by christomaszewski** [comment]
It does this already. Are you on the latest version?

**Comment by jjblum** [comment]
What is the latest version to you? I build from the Debug branch.

**Comment by christomaszewski** [comment]
Idk, wherever Shantanu builds from. We need to organize our repo like we
have done with firmware and server.

**Comment by shantanu-vyas** [comment]
Right now the app pushes default PID values to the boat when it connects. When you press set pids it should set those text fields to whatever the boat then has as those PIDs.

**Comment by jjblum** [comment]
RE: organizing the repo:    I think the way Shantanu has this repo is the proper form. Master branch for full release code, Debug as a more incremental aggregator of smaller fixes/feature, and small feature branches. I will recheck what apk the UK guy has and double check my Debug branch build to make sure it hasn't already been fixed on my version i.e. the UK guy has an older apk.

RE: showing the values:     "When you press set pids it should set those text fields to whatever the boat then has as those PIDs."    That seems backwards. You should have those values displayed before pressing the set button. Because my first instinct as a user is that if I press the set PID button it will set all of them to the displayed values, i.e. all zeros.

**Comment by christomaszewski** [comment]
See sever and firmware for proper form.

**Comment by shantanu-vyas** [comment]
@jjblum If you look https://github.com/platypusllc/tablet/blob/Debug/app/src/main/java/com/platypus/android/tablet/TeleOpPanel.java#L2099 
The app grabs the PIDS and sets it to those text fields. Also I'm a little confused because the app should send the PID's on connect because I wrote that a couple days back but its not in the debug branch?

**Comment by jjblum** [comment]
Okay, I confirm it works in the Debug branch. I will get Mark an updated apk. One new observation though (and we can put this in a new issue if you'd prefer), the floating point numbers are causing tiny decimal places to be nonzero (e.g. default thrust is 0.10000000149011612). Either round it or cast it into a formatted string with no more than 4 decimal places.

**Comment by shantanu-vyas** [comment]
Ah didn't see that happening. Will fix.

**Comment by jjblum** [comment]
You fixed this before, but the Debug branch is back to doing this again on my Kindle fire tablet.

**Comment by jjblum** [comment]
The more recent "preferences_api"-based branches have resolved this issue.
