### ISSUE TITLE
mapbox 4.2.0-SNAPSHOT not found

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#24]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT.
     Required by:
         tablet:app:unspecified

Looks like MapBox has been updated. We need to update the build.gradle file to accommodate the change.

**Comment by jjblum** [comment]
Mapbox website has the snapshot updated to 4.2.1
Changing build.gradle to have 4.2.1 instead of 4.2.0 fixed the issue.

**Comment by shantanu-vyas** [comment]
Every time a new update comes for mapbox that changes the version number this happens. I'm not sure if there is some way to have it automatically pull the newest snapshot/stable. If you get that error again in the future you have to look at https://www.mapbox.com/android-sdk/ and replace that stable/snapshot with the new version number.
