### ISSUE TITLE
Sensor Pod and Winch 

### ISSUE THREAD

**Issue by shantanu-vyas** [platypusllc/tablet#25]
Sensor Pod

- Show All 4 Sensor Pods in the Sensor Box in the bottom sensor panel.
- After button is pressed turn into checkmark. Send command through setGains with specific axis for each sensor pod.

Winch
- Add roller for adding and subtracting length.
- Show current length
- Add return button (sets length to 0)

**Comment by psigen** [comment]
Can you post a screenshot of the new interface features?  It will be useful for tracking this change later.
