### ISSUE TITLE
preference_api crash on connect button press with default install IP address

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#26]
On a fresh install of this branch, if you press connect in the Connect to a Boat dialog that pops up, the app crashes. Once I put in another IP, it did not crash and connects normally.

**Comment by shantanu-vyas** [comment]
I noticed this too, looking into it tonight or tomorrow. I think its caused by the initial default value for the boats IP.

**Comment by psigen** [comment]
Thanks Shantanu. You can copy the code we use in the server to initialize
the default values for the preferences from a string resource.
