### ISSUE TITLE
Propeller keeps running when joystick return to zero 

### ISSUE THREAD

**Issue by Zeshengx** [platypusllc/tablet#4]
Propeller is uncontrolled by teleoperating (not latency) under unknown condition. Keep running unless turning off the eboard. Moving joystick wouldn't stop the propeller.

**Comment by psigen** [comment]
Can you test if the debug panel on the one-touch server can stop the propeller in this case?

**Comment by Zeshengx** [comment]
Yes, I will test that once I can reproduce the issue.
